### ISSUE TITLE
Not able to print whole page

### ISSUE THREAD

**Issue by kentraub** [RickStrahl/HelpBuilderReleases#104]
[test.pdf](https://github.com/RickStrahl/HelpBuilderReleases/files/4489957/test.pdf)
When we attempt to print a page from our help file it cuts off most of the page.  Do you have any recommendations to print a page properly?

**Comment by kentraub** [comment]
I did find if I remove the overflow:hidden from the body, it prints properly when previewed in Chrome.  Is there a way to change the viewing browser used in the help file or what change is needed to print properly in ie or firefox browsers?

**Comment by RickStrahl** [comment]
Hmm... yes there's not a whole lot of thought given to the stock templates for printing. For printing it's best to use the MSWORD theme which is set up for printing and removes the internal frames.

That said you can fix existing topics using the standard screen themes with this in the `wwhelp.css` style sheet (**Tree | Edit Topic Templates | Edit CSS Style Sheet**). Then add this at the bottom:

```css
@media print {
    html, body {
        overflow: visible;
    }
    .main-content {
        overflow: visible;
    }
    .flex-master, .main-content { display: block} 
	.sidebar-left, .hidable, .sidebar-toggle, .splitter
	{display: none} 
	pre {
	    white-space: pre-wrap;
	}
}
```

The`@media print` section already exists but the overflow vars are new.

This makes the existing topics work:

![image](https://user-images.githubusercontent.com/1374013/79838616-ffc4d980-834e-11ea-815b-c101191f91dc.png)
)

Adding this to the default template styles.

Thanks.
