### ISSUE TITLE
HTML templates - print page problem.

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/HelpBuilderReleases#44]
Long Html page generated from original templates cannot be printed whole.
Browser prints only first page with scrollbar picture.
Can You change templates to make whole topic printable?
Thank You.

**Comment by RickStrahl** [comment]
How are you printing?

**Comment by zdenekkrejci** [comment]
Open help in web browser.
Open long page, Press CTRL+P.
Edge, IE, Opera - the same result.

**Comment by zdenekkrejci** [comment]
I suggest this solution

``css
@media print {
.flex-master, .main-content { display: block}
.sidebar-left, .banner {display: none} 
}
` `

**Comment by RickStrahl** [comment]
Thank you.

Here's what I used and added:

``` css
@media print {
     .flex-master, .main-content { display: block} 
     .sidebar-left, .hidable, .sidebar-toggle
     {display: none} 
     pre {
        white-space: pre-wrap;
     }
}
```

 I think we do want to keep the banner for identification, but of course it's customizable by the user as necessary.

Thanks a lot. I meant to look into this and forgot. The default templates look quite nice printed (or previewed).
